trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
   - job : job1
     steps:
       - bash : echo build first job
       - bash : java -version
       - bash : node --version
       - bash : python --version
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*.yaml
        **/*.tf
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


