
trigger:
- master

resources:
- repo: self

variables:
  tag: 23
  
  #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    #- task: Docker@2
     # displayName: Build an image
      #inputs:
       # containerRegistry: 'sundar-docker-hub'
        #repository: 'sundarhub/currency-exchange'
        #command: 'buildAndPush'
        #Dockerfile: '**/Dockerfile'
       # tags: '$(tag)'
    #- task: CopyFiles@2
      #inputs:
      #  SourceFolder: '$(System.DefaultWorkingDirectory)'
       # Contents: '**/*.yaml'
       # TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'sundarhub/currency-exchange:$(tag)'